TWOCC_FORMATS = {
  # rfc2361    (Name,             Extended Format, exact RIFF WAVE FMT EXT size)
  0x0000: ('MS Unknown',                    False, None),
  0x0001: ('PCM',                           False, None),
  0x0002: ('MS ADPCM',                      True,  None),
  0x0003: ('IEEE Float',                    True,  None),
  0x0004: ('Compaq VSELP',                  True,  None),
  0x0005: ('IBM CVSD',                      True,  0),
  0x0006: ('A-law',                         True,  0),
  0x0007: ('mu-law',                        True,  None),
  0x0008: ('MS DTS',                        False, None),
  0x0009: ('MS DRM',                        True,  None),
  0x0010: ('OKI ADPCM',                     True,  2),
  0x0011: ('Intel DVI/IMA ADPCM',           True,  2),
  0x0012: ('Videologic MediaSpace ADPCM',   True,  None),
  0x0013: ('Sierra ADPCM',                  True,  None),
  0x0014: ('G.723 ADPCM',                   True,  None),
  0x0015: ('DSP Solution DigiSTD',          True,  0),
  0x0016: ('DSP Solution DigiFIX',          True,  0),
  0x0017: ('Dialogic OKI ADPCM',            True,  0),
  0x0018: ('MediaVision ADPCM',             True,  None),
  0x0019: ('HP CU',                         True,  None),
  0x0020: ('Yamaha ADPCM',                  True,  0),
  0x0021: ('Speech Compression Sonarc',     True,  0),
  0x0022: ('DSP Group TrueSpeech',          True,  0x20),
  0x0023: ('Echo Speech EchoSC1',           True,  0),
  0x0024: ('Audiofile AF36',                True,  None),
  0x0025: ('APTX',                          True,  0),
  0x0026: ('AudioFile AF10',                True,  None),
  0x0027: ('Prosody 1612',                  True,  None),
  0x0028: ('LRC',                           True,  None),
  0x0030: ('Dolby AC2',                     True,  None),
  0x0031: ('GSM610',                        True,  None),
  0x0032: ('MSNAudio',                      True,  None),
  0x0033: ('Antex ADPCME',                  True,  None),
  0x0034: ('Control Res VQLPC',             True,  2),
  0x0035: ('Digireal',                      True,  None),
  0x0036: ('DigiADPCM',                     True,  None),
  0x0037: ('Control Res CR10',              True,  None),
  0x0038: ('NMS VBXADPCM',                  True,  None),
  0x0039: ('Roland RDAC',                   True,  None),
  0x003A:( 'EchoSC3',                       True,  None),
  0x003B:( 'Rockwell ADPCM',                True,  None), 
  0x003C:( 'Rockwell Digit LK',             True,  None),
  0x003D:( 'Xebec',                         True,  None),
  0x0040: ('G.721 ADPCM',                   True,  None),
  0x0041: ('G.728 CELP',                    True,  None),
  0x0042: ('MSG723',                        True,  None),
  0x0043: ('IBM AVC ADPCM',                 True,  None),
  0x0045: ('ITU-T G.726 ADPCM',             True,  None),
  0x0050: ('MPEG 1',                        True,  None),
  0x0052: ('RT24',                          True,  None),
  0x0053: ('PAC',                           True,  None),
  0x0055: ('MPEG Layer 3',                  True,  None),
  0x0059: ('Lucent G.723',                  True,  None),
  0x0060: ('Cirrus',                        True,  None),
  0x0061: ('ESPCM',                         True,  None),
  0x0062: ('Voxware',                       True,  None),
  0x0063: ('Canopus Atrac',                 True,  None),
  0x0064: ('G.726 ADPCM',                   True,  None),
  0x0065: ('G.722 ADPCM',                   True,  None),
  0x0066: ('DSAT',                          True,  None),
  0x0067: ('DSAT Display',                  True,  None),
  0x0069: ('Voxware Byte Aligned',          True,  None),
  0x0070: ('Voxware AC8',                   True,  None),
  0x0071: ('Voxware AC10',                  True,  None),
  0x0072: ('Voxware AC16',                  True,  None),
  0x0073: ('Voxware AC20',                  True,  None),
  0x0074: ('Voxware MetaVoice',             True,  None),
  0x0075: ('Voxware MetaSound',             True,  None),
  0x0076: ('Voxware RT29HW',                True,  None),
  0x0077: ('Voxware VR12',                  True,  None),
  0x0078: ('Voxware VR18',                  True,  None),
  0x0079: ('Voxware TQ40',                  True,  None),
  0x0080: ('Softsound',                     True,  None),
  0x0081: ('Voxware TQ60',                  True,  None),
  0x0082: ('MSRT24',                        True,  None),
  0x0083: ('G.729A',                        True,  None),
  0x0084: ('MVI MV12',                      True,  None),
  0x0085: ('DF G.726',                      True,  None),
  0x0086: ('DF GSM610',                     True,  None),
  0x0088: ('ISIAudio',                      True,  None),
  0x0089: ('Onlive',                        True,  None),
  0x0091: ('SBC24',                         True,  None),
  0x0092: ('Dolby AC3 SPDIF',               False, None),
  0x0093: ('MediaSonic G.723',              True,  None),
  0x0094: ('Aculab PLC Prosody 8kbps',      True,  None),
  0x0097: ('ZyXEL ADPCM',                   True,  None),
  0x0098: ('Philips LPCBB',                 True,  None),
  0x0099: ('Packed',                        True,  None),
  0x00A0: ('Malden Electronics PHONYTALK',  True,  None),
  0x00FF: ('AAC',                           True,  None),
  0x0100: ('Rhetorex ADPCM',                True,  None),
  0x0101: ('BeCubed Software IRAT' '/IBM Mu-law',
                                            True,  None),
  0x0102: ('IBM A-law',                     True,  None),
  0x0103: ('IBM ADPCM',                     True,  None),
  0x0111: ('Vivo G.723',                    True,  None),
  0x0112: ('Vivo Siren',                    True,  None),
  0x0123: ('Digital G.723',                 True,  None),
  0x0125: ('Sanyo LD ADPCM',                True,  None),
  0x0130: ('Sipro Lab Telecom ACELP.net',   True,  None),
  0x0131: ('Sipro Lab Telecom ACELP.4800',  True,  None),
  0x0132: ('Sipro Lab Telecom ACELP.8V3',   True,  None),
  0x0133: ('Sipro Lab Telecom ACELP.G.729', True,  None),
  0x0134: ('Sipro Lab Telecom ACELP.G.729A',True,  None),
  0x0135: ('Sipro Lab Telecom ACELP.KELVIN',True,  None),
  0x0140: ('Windows Media Video V8',        True,  None),
  0x0150: ('Qualcomm PureVoice',            True,  None),
  0x0151: ('Qualcomm HalfRate',             True,  None),
  0x0155: ('Ring Zero Systems TUB GSM',     True,  None),
  0x0160: ('WMA V1 / DivX audio',           True,  None),
  0x0161: ('WMA V7,8,9',                    True,  None),
  0x0162: ('WMA Pro V9',                    True,  None),
  0x0163: ('WMA Lossless V9',               True,  None),
  0x0164: ('WMA Pro SPDIF',                 True,  None),
  0x0170: ('UNISYS NAP ADPCM',              True,  None),
  0x0171: ('UNISYS NAP ULAW',               True,  None),
  0x0172: ('UNISYS NAP ALAW',               True,  None),
  0x0173: ('UNISYS NAP 16K',                True,  None),
  0x0200: ('Creative ADPCM',                True,  2),
  0x0202: ('Creative FastSpeech8',          True,  None),
  0x0203: ('Creative FastSpeech10',         True,  None),
  0x0210: ('UHER Informatic ADPCM',         True,  None),
  0x0215: ('Ulead DV ACM',                  True,  None),
  0x0216: ('Ulead DV ACM',                  True,  None),
  0x0220: ('Quarterdeck',                   True,  None),
  0x0230: ('I-link Worldwide ILINK VC',     True,  None),
  0x0240: ('Aureal Semiconductor RAW SPORT',True,  None),
  0x0241: ('ESST AC3',                      True,  None),
  0x0250: ('Interactive Products HSX',      True,  None),
  0x0251: ('Interactive Products RPELP',    True,  None),
  0x0260: ('Consistent Software CS2',       True,  None),
  0x0270: ('Sony ATRAC3 (SCX, same as MiniDisk LP2)',
                                            True,  None),
  0x0300: ('Fujitsu FM Towns Snd',          True,  None),
  0x0400: ('BTV Digital',                   True,  None),
  0x0401: ('Intel Music Coder (IMC)',       True,  None),
  0x0402: ('Ligos Indeo Audio',             True,  None),
  0x0450: ('QDesign Music',                 True,  None),
  0x0680: ('VME VMPCM',                     True,  None),
  0x0681: ('AT&T Labs TPC',                 True,  None),
  0x0700: ('YMPEG Alpha',                   True,  None),
  0x08AE: ('ClearJump LiteWave',            True,  None),
  0x1000: ('Olivetti GSM',                  True,  None),
  0x1001: ('Olivetti ADPCM',                True,  None),
  0x1002: ('Olivetti CELP',                 True,  None),
  0x1003: ('Olivetti SBC',                  True,  None),
  0x1004: ('Olivetti OPR',                  True,  None),
  0x1100: ('Lernout & Hauspie LH',          True,  None),
  0x1101: ('Lernout & Hauspie CELP',        True,  None),
  0x1102: ('Lernout & Hauspie SBC',         True,  None),
  0x1103: ('Lernout & Hauspie SBC',         True,  None),
  0x1104: ('Lernout & Hauspie SBC',         True,  None),
  0x1400: ('Norris',                        True,  None),
  0x1401: ('AT&T ISIAudio',                 True,  None),
  0x1500: ('Soundspace Music Compression',  True,  None),
  0x1610: ('HE-ACC',                        True,  None),
  0x181C: ('VoxWare RT24 speech',           True,  None),
  0x181E: ('Lucent elemedia AX24000P Music',True,  None),
  0x1C07: ('Lucent SX8300P speech',         True,  None),
  0x1C0C: ('Lucent SX5363S G.723 compliant',True,  None),
  0x1F03: ('CUseeMe DigiTalk (ex-Rocwell)', True,  None),
  0x1FC4: ('NCT Soft ALF2CD ACM',           True,  None),
  0x2000: ('AC3 / DVM',                     True,  None),
  0x2001: ('Dolby DTS (Digital Theater System)',
                                            True,  None),
  0x2002: ('RealAudio 1 / 2 14.4',          True,  None),
  0x2003: ('RealAudio 1 / 2 28.8',          True,  None),
  0x2004: ('RealAudio G2 / 8 Cook (low bitrate)',
                                            True,  None),
  0x2005: ('RealAudio 3 / 4 / 5 Music (DNET)',
                                            True,  None),
  0x2006: ('RealAudio 10 AAC (RAAC)',       True,  None),
  0x2007: ('RealAudio 10 AAC+ (RACP)',      True,  None),
  0x3313: ('makeAVIS',                      True,  None),
  0x4143: ('Divio MPEG-4 AAC audio',        True,  None),
  0x434C: ('LEAD Speech',                   True,  None),
  0x564C: ('LEAD Vorbis',                   True,  None),
  0x674F: ('Ogg Vorbis (mode 1)',           True,  None),
  0x6750: ('Ogg Vorbis (mode 2)',           True,  None),
  0x6751: ('Ogg Vorbis (mode 3)',           True,  None),
  0x676F: ('Ogg Vorbis (mode 1+)',          True,  None),
  0x6770: ('Ogg Vorbis (mode 2+)',          True,  None),
  0x6771: ('Ogg Vorbis (mode 3+)',          True,  None),
  0x7A21: ('GSM-AMR (CBR, no SID)',         True,  None),
  0x7A22: ('GSM-AMR (VBR, including SID)',  True,  None),
  0xDFAC: ('DebugMode SonicFoundry Vegas FrameServer ACM',
                                            True,  None),
  0xF1AC: ('Free Lossless Audio Codec FLAC',True,  None),
  0xFFFE: ('Extensible',                    True,  None),
  0xFFFF: ('development',                   True,  None),
};